point_cloud_topic: "/plane_removed"
# sensor_frame_id: "lens_link"
map_frame_id: "robot_base"
robot_base_frame_id: "robot_base"
robot_pose_with_covariance_topic: "/pose"
robot_pose_cache_size: 200
track_point_frame_id: "robot_base"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
